[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/product_pages/*"
  to = "/product_pages/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200