[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  VITE_SERVER_URL = "https://wdd330-backend.onrender.com/"

[[redirects]]
  from = "/product_pages/*"
  to = "/product_pages/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
